Fix netty/boring incompatibility that cause the following error in Broker:
2020-03-25T13:27:59.469Z WARN  [ChannelInitializer] Failed to initialize a channel. Closing: [id: 0xb2589fd9]
java.lang.NoClassDefFoundError: io/netty/internal/tcnative/SSLPrivateKeyMethod
        at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:827)

problem caused by 'Update netty version to 4.1.44.Final (#3813)'